GET http://localhost/api/health-check

###
GET http://localhost/api/posts

###
POST http://localhost/api/posts
Content-Type: application/json

{
    "title": "First Post",
    "content": "Some Content"
}

###
GET http://localhost/api/posts/1


###
PUT http://localhost/api/posts/1
Content-Type: application/json

{
    "title": "First Post Changed",
    "content": "Some Content Changed"
}


###
DELETE http://localhost/api/posts/1
