version: '3'
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:alpine
    volumes:
      - .:/var/www/html:ro
      - ./storage/nginx:/var/log/nginx/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: lara_docker:dev
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: asdf
    volumes:
    - ./storage/mysql:/var/lib/mysql
    ports:
      - 33061:3306

  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    image: adminer:latest
    restart: always
    ports:
    - 8081:8080
